Mui card
TurtleWolfe/tmx pull request #4
Opened 2022-02-17 05:17 UTC by TurtleWolfe

I'll work more on making it look like the prototype with stars and such tomorrow, but passing the props is scaffold in
![Screenshot 2022-02-17 at 00-04-29 🏍️ tMX](https://user-images.githubusercontent.com/7327259/154410335-78bb9119-16ef-4e2d-a442-2e5763f1c4fa.png)

2022-02-17 20:41 UTC, NullDefault requested changes

2022-02-17 20:41 UTC, NullDefault commented on src/components/muiCard.js
> +
filename should be different - all of your components are mui, why specify it.
In general, filenames should be the same as the Component name

2022-02-17 20:41 UTC, NullDefault commented on src/components/muiCard.js
> +import Card from '@mui/material/Card';
Don't import these things one by one - you can import all the things in one line
i.e
import {Card, CardContent} from "@mui/material"
Look at the other files - it's done like that everywhere

2022-02-17 20:41 UTC, NullDefault commented on src/components/muiCard.js
> +import { Button, CardActionArea, CardActions } from '@mui/material';
Yeah everything should be imported like this

2022-02-17 20:41 UTC, NullDefault commented on src/components/muiCard.js
> +        // src={svg_art}
remove comments before eventual merge

2022-02-17 21:04 UTC, TurtleWolfe commented on src/components/muiCard.js
> +
I was thinking to specify it as a custom component,
I don't mind changing the name
 but there are other places we may want to just use the standard Card and it gets confusing.

2022-02-17 21:05 UTC, TurtleWolfe commented on src/components/muiCard.js
> +import Card from '@mui/material/Card';
ok, I copied from the `docs`, but I see what you mean

2022-02-18 00:17 UTC, NullDefault commented on src/components/muiCard.js
> +
Can you elaborate on what you mean by the standard Card?

2022-02-18 15:13 UTC, TurtleWolfe commented
I'm squashing this so Bobe can use it in his map Component

2022-02-18 15:15 UTC, merged